// This file is automatically generated. Do not edit directly.
// Generated on: 2025-07-12T00:25:20.252Z

// Import all configured plugins
import bibtexCollaborative_viewersPlugin from './collaborative_viewers/bibtex';
import bibtexViewersPlugin from './viewers/bibtex';
import imageViewersPlugin from './viewers/image';
import pdfViewersPlugin from './viewers/pdf';
import pdfRenderersPlugin from './renderers/pdf';
import latex_visualizerLoggersPlugin from './loggers/latex_visualizer';
import githubBackupPlugin from './backup/github';
import choutex_slimThemesPlugin from './themes/choutex_slim';
import choutex_wideThemesPlugin from './themes/choutex_wide';

// Export individual plugins
export {
  bibtexCollaborative_viewersPlugin,
  bibtexViewersPlugin,
  imageViewersPlugin,
  pdfViewersPlugin,
  pdfRenderersPlugin,
  latex_visualizerLoggersPlugin,
  githubBackupPlugin,
  choutex_slimThemesPlugin,
  choutex_wideThemesPlugin
};

// Export collaborative_viewers plugins as a group
export const collaborative_viewers = {
  bibtexCollaborative_viewersPlugin
};

// Export viewers plugins as a group
export const viewers = {
  bibtexViewersPlugin,
  imageViewersPlugin,
  pdfViewersPlugin
};

// Export renderers plugins as a group
export const renderers = {
  pdfRenderersPlugin
};

// Export loggers plugins as a group
export const loggers = {
  latex_visualizerLoggersPlugin
};

// Export backup plugins as a group
export const backup = {
  githubBackupPlugin
};

// Export themes plugins as a group
export const themes = {
  choutex_slimThemesPlugin,
  choutex_wideThemesPlugin
};

